### ISSUE TITLE
Use regex in replace() for cross browser compatibility

### ISSUE THREAD

**Issue by shinglyu** [shinglyu/moztrap-new-ui#2]
The `replace("\"", "", "g")` (in `parser.js`) should be changed to `replace(/\"/g, ''")` to support Chrome.

**Comment by shinglyu** [comment]
Temporary enabled on `gh-pages` branch, should merge to master after testing

**Comment by yodalee** [comment]
Should `'` also be trimmed? I test name:'firefox' and it will get nothing

**Comment by yodalee** [comment]
Should `'` also be trimmed? I test name:'firefox' and it will get nothing

**Comment by shinglyu** [comment]
Yes, there are several bugs in the parser, but we will (hopefully) fix them all in https://github.com/shinglyu/moztrap-new-ui/issues/81

**Comment by yodalee** [comment]
I mean this can be solve by using the regex `/["']/g`

**Comment by shinglyu** [comment]
Sure, I'll merge it if you open a PR.
